// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:private_deals/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jj5g7MKEbagYkiKSAuC5e3yManx5YDY',
    appId: '1:749470263169:web:c36d2fd936afca1c4e2a80',
    messagingSenderId: '749470263169',
    projectId: 'private-deals-e672b',
    authDomain: 'private-deals-e672b.firebaseapp.com',
    storageBucket: 'private-deals-e672b.firebasestorage.app',
    measurementId: 'G-HS6FVQDDFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj3w1cUteGoEqxxDn06cP6jzEfbFKeQbk',
    appId: '1:749470263169:android:915811d415ebd57a4e2a80',
    messagingSenderId: '749470263169',
    projectId: 'private-deals-e672b',
    storageBucket: 'private-deals-e672b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9TOYJNJp6Nw8gBwWm6fx_71Q8nbUe2jk',
    appId: '1:749470263169:ios:455d3c6a6273909a4e2a80',
    messagingSenderId: '749470263169',
    projectId: 'private-deals-e672b',
    storageBucket: 'private-deals-e672b.firebasestorage.app',
    iosBundleId: 'com.privatedeals.partner',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9TOYJNJp6Nw8gBwWm6fx_71Q8nbUe2jk',
    appId: '1:749470263169:ios:455d3c6a6273909a4e2a80',
    messagingSenderId: '749470263169',
    projectId: 'private-deals-e672b',
    storageBucket: 'private-deals-e672b.firebasestorage.app',
    iosBundleId: 'com.privatedeals.partner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jj5g7MKEbagYkiKSAuC5e3yManx5YDY',
    appId: '1:749470263169:web:c36d2fd936afca1c4e2a80',
    messagingSenderId: '749470263169',
    projectId: 'private-deals-e672b',
    authDomain: 'private-deals-e672b.firebaseapp.com',
    storageBucket: 'private-deals-e672b.firebasestorage.app',
    measurementId: 'G-HS6FVQDDFE',
  );
}
