import 'smoke_case.dart';

/// Full checklist from the API smoke-test plan (#1–46 + skips).
List<SmokeCase> smokeChecklist() => const [
      // Priority 1
      SmokeCase(
        id: 1,
        feature: 'Portfolio → Primary sell share',
        apiLabel: 'InvestorSecondaryTransactionApi.primarySellRequest',
        method: SmokeMethod.post,
        pathSuffix: 'v1/investor/secondary-invest/sell-now',
        priority: SmokePriority.p1,
        role: SmokeRole.wealthManager,
        readOnly: false,
        mismatchNote:
            'WM UI calls investor path; Dio interceptor rejects /investor/ for partners — use wSellNow',
      ),
      SmokeCase(
        id: 2,
        feature: 'Portfolio → Pre-IPO sell share',
        apiLabel: 'WPreIpoTransactionApi.preIPOSellRequest',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/pre-ipo/sell',
        priority: SmokePriority.p1,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 3,
        feature: 'Channel Partner → List',
        apiLabel: 'ChannelPartnerApi.channelPartnerList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/channel-partner',
        priority: SmokePriority.p1,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 4,
        feature: 'Channel Partner → Add',
        apiLabel: 'ChannelPartnerApi.addChannelPartner',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/channel-partner',
        priority: SmokePriority.p1,
        role: SmokeRole.wealthManager,
        readOnly: false,
        mismatchNote:
            'Body maps is_*_access from password field; verify server accepts',
      ),
      SmokeCase(
        id: 5,
        feature: 'Portfolio → List primary / pre-IPO',
        apiLabel: 'PortfolioApi.wPortfolioAPi / wPreIpoPortfolioAPi',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/portfolio/startup',
        priority: SmokePriority.p1,
        role: SmokeRole.wealthManager,
        mismatchNote:
            'Pre-IPO list builds investor_ids but may call get(..., {}); also smoke pre-ipo path',
      ),

      // Priority 2
      SmokeCase(
        id: 6,
        feature: 'Upload portfolio',
        apiLabel: 'PortfolioApi.getCompanyStartupApi / wAddPortfolioApi',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/company-startup-list',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 7,
        feature: 'Investors → list / filters',
        apiLabel: 'WInvestorsApi.investorsList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/investor',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 8,
        feature: 'Investors → add / update',
        apiLabel: 'WInvestorsApi.addInvestor',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/investor',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 9,
        feature: 'Investors → detail',
        apiLabel: 'WInvestorsApi.getInvestor',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/investor/detail',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 10,
        feature: 'KYC → CML read/save',
        apiLabel: 'CmlApi.read / save',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/investor/kyc/cml/read',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 11,
        feature: 'KYC → legacy doc upload',
        apiLabel: 'WealthManagerKycApi.kycUpdate',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/investor-kyc',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 12,
        feature: 'Pending tasks',
        apiLabel: 'PendingTaskApi.pendingTasks',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/pending-tasks',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 13,
        feature: 'Primary TX list',
        apiLabel: 'WPrimaryTransactionApi.transactionList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/primary-transactions',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 14,
        feature: 'Primary invest-now',
        apiLabel: 'InvestorPrimaryTransactionApi.wealthManagerInvestment',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/primary-invest/invest-now',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 15,
        feature: 'Primary payment receipt',
        apiLabel: 'InvestorPrimaryTransactionApi.paymentReceipt',
        method: SmokeMethod.post,
        pathSuffix: 'v1/investor/primary-invest/upload-payment-receipt',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
        mismatchNote:
            'WM uses investor upload-payment-receipt; Dio interceptor rejects /investor/ for partners',
      ),
      SmokeCase(
        id: 16,
        feature: 'Secondary TX list',
        apiLabel: 'WSecondaryTransactionApi.secondaryTransactionList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/secondary-invest/transactions/list',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 17,
        feature: 'Secondary sell-request list',
        apiLabel: 'WSecondaryTransactionApi.sellRequestList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/secondary-invest/sell-request',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 18,
        feature: 'Secondary opportunities + ROFR',
        apiLabel: 'WSecondaryTransactionApi.opportunitiesList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/secondary-invest/related-oppotunities',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 19,
        feature: 'Secondary receipt upload / approve',
        apiLabel: 'WSecondaryTransactionApi.shareReceiptApprove',
        method: SmokeMethod.post,
        pathSuffix:
            'v1/business/secondary-invest/transactions/share-receipt-approve',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 20,
        feature: 'Secondary buy (if wired)',
        apiLabel: 'WSecondaryTransactionApi.buyRequest',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/secondary-invest/buy-now',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
        mismatchNote: 'No WM UI caller found; API exists but may be dead',
      ),
      SmokeCase(
        id: 21,
        feature: 'Pre-IPO sell TX list',
        apiLabel: 'WPreIpoTransactionApi.sellTransactionList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/pre-ipo/sell-transaction',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 22,
        feature: 'Pre-IPO buy TX lifecycle',
        apiLabel: 'WPreIpoTransactionApi.transactionList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/pre-ipo/transaction-list',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 23,
        feature: 'Send document',
        apiLabel: 'DocumentApi.sendDocument',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/send-document',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 24,
        feature: 'My earnings',
        apiLabel: 'MyEarningApi.wInvestorEarningList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/earning/investor',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 25,
        feature: 'MIS',
        apiLabel: 'MisApi.wMisList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/invested-startup-mis',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 26,
        feature: 'Notifications',
        apiLabel: 'NotificationApi.wNotificationList',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/notifications',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        mismatchNote: 'WM notifications tab is empty Container(); use /notification',
      ),
      SmokeCase(
        id: 27,
        feature: 'Dashboard',
        apiLabel: 'DashboardApi.wealthManagerDashboard',
        method: SmokeMethod.get,
        pathSuffix: 'v1/business/dashboard',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 28,
        feature: 'Catalog enquiry create',
        apiLabel: 'WPreIpoTransactionApi.inquiry',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/enquiries/deals',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 29,
        feature: 'My inquiries list',
        apiLabel: 'EnquiryApi.list',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/enquiries/deals',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 30,
        feature: 'Pre-IPO buy place order',
        apiLabel: 'WPreIpoTransactionApi.buy',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/pre-ipo/buy',
        priority: SmokePriority.p2,
        role: SmokeRole.wealthManager,
        readOnly: false,
      ),
      SmokeCase(
        id: 31,
        feature: 'Auth login',
        apiLabel: 'WAuthApi.login',
        method: SmokeMethod.post,
        pathSuffix: 'v1/business/login',
        priority: SmokePriority.p2,
        role: SmokeRole.either,
        readOnly: false,
      ),
      SmokeCase(
        id: 32,
        feature: 'Inquiry (public lead)',
        apiLabel: 'IAuthApi.verifyMobileNumber',
        method: SmokeMethod.post,
        pathSuffix: 'verify-mobile-number',
        priority: SmokePriority.p2,
        role: SmokeRole.public,
        readOnly: false,
      ),

      // Priority 3 Institution
      SmokeCase(
        id: 33,
        feature: 'Institution dashboard',
        apiLabel: 'DashboardApi.getDashboard',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/dashboard',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 34,
        feature: 'Company list',
        apiLabel: 'CompanyApi.getCompanyList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/company/list',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 35,
        feature: 'Create company sectors',
        apiLabel: 'CompanyApi.getSectorList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/company/sectors',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 36,
        feature: 'Promoters',
        apiLabel: 'CompanyApi.savePromoters',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/institution/company/promoters',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
        readOnly: false,
      ),
      SmokeCase(
        id: 37,
        feature: 'Deal list',
        apiLabel: 'DealApi.getDealList',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/company/deals',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 38,
        feature: 'Bulk / update share price',
        apiLabel: 'DealApi.bulkDeals',
        method: SmokeMethod.post,
        pathSuffix: 'v2/business/institution/company/deals/bulk',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
        readOnly: false,
      ),
      SmokeCase(
        id: 39,
        feature: 'Unlisted TX list',
        apiLabel: 'PreIPOTransactionApi.getTransactions',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/pre-ipo/transaction',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 40,
        feature: 'Institution sell enquiries',
        apiLabel: 'EnquiryApi.list(institution: true)',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/enquiries',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 41,
        feature: 'Institution public profile',
        apiLabel: 'InstitutionProfileApi.getProfile',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/institution/profile',
        priority: SmokePriority.p3,
        role: SmokeRole.institution,
      ),
      SmokeCase(
        id: 42,
        feature: 'LP secondary transactions UI',
        apiLabel: '(none)',
        method: SmokeMethod.get,
        pathSuffix: '(none)',
        priority: SmokePriority.skip,
        role: SmokeRole.institution,
        skipReason: 'Placeholder UI — no API',
      ),

      // Catalog browse
      SmokeCase(
        id: 43,
        feature: 'Primary home',
        apiLabel: 'LandingPageApi.wHomePage',
        method: SmokeMethod.get,
        pathSuffix: 'v1/get-home',
        priority: SmokePriority.catalog,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 44,
        feature: 'Pre-IPO home',
        apiLabel: 'PreIpoLandingPageApi.wPreIPOHome',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/home/pre-ipo',
        priority: SmokePriority.catalog,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 45,
        feature: 'Secondary home',
        apiLabel: 'PreIpoLandingPageApi.wSecondaryHome',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/home/secondary',
        priority: SmokePriority.catalog,
        role: SmokeRole.wealthManager,
      ),
      SmokeCase(
        id: 46,
        feature: 'News / sectors',
        apiLabel: 'PreIpoLandingPageApi.newsSectors',
        method: SmokeMethod.get,
        pathSuffix: 'v2/business/home/pre-ipo/news-sectors',
        priority: SmokePriority.catalog,
        role: SmokeRole.wealthManager,
      ),
    ];

List<SmokeCase> byPriority(SmokePriority p) =>
    smokeChecklist().where((c) => c.priority == p).toList();

List<SmokeCase> mismatchFlags() =>
    smokeChecklist().where((c) => c.mismatchNote != null).toList();
